### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by SITUVNgcd**
Translate bundle to Vietnamese

### CODE REVIEW

**Comment by Darkness6030** [comment]
Sorry for responding very late, will review this someday

**Comment by SITUVNgcd** [comment]
> Sorry for responding very late, will review this someday

I don't think you will review this, thanks!
I translated all public repo for Darkdustry server, wish you will review all of them.

**Comment by SITUVNgcd** [comment]
I just checked and found some encoding issue, fixed it and add 2 new bundle strings.

**Comment by 5GameMaker** [comment]
Looks good

**Pull request merged**
